### ISSUE TITLE
Server version mismatch

### ISSUE THREAD

**Issue by paulrudy** [tj-actions/pg-dump#132]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does this issue exist in the latest version?

- [X] I'm using the latest release

### Describe the bug?

I'm proxying a database connection to a Postgres app hosted on fly.io. I receive the following error:
```
pg_dump: error: server version: 15.3 (Debian 15.3-1.pgdg120+1); pg_dump version: 14.9 (Ubuntu 14.9-1.pgdg22.04+1)
pg_dump: error: aborting because of server version mismatch
Error: Process completed with exit code 1.
```

I've seen in #35 that the action should be agnostic regarding Postgres versions, so I've filed this as a bug.

### To Reproduce

```
name: Backup postgres database
on:
  workflow_dispatch: 
jobs:
  backup:
    name: Postgres backup
    runs-on: ubuntu-latest
    env:
      FLY_API_TOKEN: ${{ secrets.FLY_POSTGRES_APP_API_TOKEN }}
      POSTGRES_APP_NAME: ${{ vars.POSTGRES_APP_NAME }}
      PG_PASSWORD: ${{ secrets.POSTGRES_PASS }}
      PG_USER: ${{ vars.POSTGRES_USER }}
      PG_DBNAME: ${{ vars.POSTGRES_DB_NAME }}
      BACKUPS_DIR: backups/postgres
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Proxy to app
        run: flyctl proxy 5432 -a ${{ env.POSTGRES_APP_NAME }} &
      - name: Get current date and time
        id: timestamp
        run: echo "TIMESTAMP=$(date +'%Y-%m-%dT%H:%M:%S%z')" >> $GITHUB_ENV
      - name: Set output path
        run: |
          echo "OUTPUT_PATH=${{ env.BACKUPS_DIR }}/db${{ env.TIMESTAMP }}.backup" >> $GITHUB_ENV
      - name: Sleep 3 seconds
        run: sleep 3
      - name: Postgres Dump Backup
        uses: tj-actions/pg-dump@v2.3
        with:
          database_url: "postgres://${{ env.PG_USER }}:${{ env.PG_PASSWORD }}@localhost:5432/${{ env.PG_DBNAME }}"
          path: ${{ env.OUTPUT_PATH }} 
          options: "-Fc"  
```

### What OS are you seeing the problem on?

ubuntu-latest or ubuntu-22.04

### Expected behavior?

completion of the action

### Relevant log output

```shell
pg_dump: error: server version: 15.3 (Debian 15.3-1.pgdg120+1); pg_dump version: 14.9 (Ubuntu 14.9-1.pgdg22.04+1)
pg_dump: error: aborting because of server version mismatch
Error: Process completed with exit code 1.
```

### Has all relevant logs been included?

- [X] I've included all relevant logs

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
