### ISSUE TITLE
[BUG] Adding more than 1 option breaks the argument

### ISSUE THREAD

**Issue by krtschmr** [tj-actions/pg-dump#42]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug?

![image](https://user-images.githubusercontent.com/13366714/138240839-2fcf2c5b-f74f-4ddc-9ed6-ca6eb7fa7935.png)

```
      - name: pg_dump into local file
        uses: tj-actions/pg-dump@v1
        with:
          database_url: "postgresql://...
          path: dump.sql
          options: -O --compress=5
```

### To Reproduce

```
      - name: pg_dump into local file
        uses: tj-actions/pg-dump@v1
        with:
          database_url: "postgresql://...
          path: dump.sql
          options: -O --compress=5
```

### What OS are you seeing the problem on?

ubuntu-latest or ubuntu-20.04

### Expected behavior?

`pg_dump -O --compress=5 -f "dump.sql" -d "***`

### Relevant log output

```shell
pg_dump "-O --compress=5" -f "dump.sql" -d "***
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
